### ISSUE TITLE
Question: how to use it in browser environment rather than node.js

### ISSUE THREAD

**Issue by hy9be** [feross/call-log#2]
Hi, would it be possible for you to give some example code for using it in a browser? Thanks!

**Comment by feross** [comment]
I just added a built file to the repo: `call-log.min.js` that you can include in your page with a `<script>` tag. Then instead of using `require('call-log')`, just use the `CallLog` function which is exported onto `window`.

```html
<script src="call-log.min.js"></script>
<script>
  function Cat () {}
  Cat.prototype.meow = function (sound) { return sound }

  // Add instrumentation to Cat
  CallLog(Cat)
</script>
```

**Comment by hy9be** [comment]
Thanks. Would it be able to log those functions defined in module?
```javascript
(function () {
	// functions defined here...
}());
```

**Comment by feross** [comment]
Yeah, but you need to call `CallLog` inside the module.
